--- # configuration settings for consumer
settings:
 connectionStrings:
  - name: azdevmaciothub
    connectionString: 'sb://iothub-ns-azdevmacio-124132-1e4aeaac71.servicebus.windows.net/'
    sasKey: ''
    sasKeyName: ''